# Generated by Django 5.1.6 on 2025-03-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('employee', 'employee')], default='employee', max_length=8),
        ),
    ]
